kind: MLApp
metadata:
  name: styles-transfer
spec:
  package_manager: pip2
  default_mount_path: "/notebooks"
  tasks:
  - name: train
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      images:
        gpu: kuberlab/tensorflow:gpu-27-1.5.0-full
        cpu: kuberlab/tensorflow:cpu-27-1.5.0-full
      command: python styles.py --job_name=worker --style=style/udnie.jpg --train_dir=$TRAINING_DIR/$BUILD_ID --test=content/chicago.jpg  --content-weight=1.5e1  --batch-size=10 --train-path=$DATA_DIR/train2014/*.jpg --vgg-path=$DATA_DIR/imagenet-vgg-verydeep-19.mat --epochs=3 --style-weight=200 --limit_train=2000 --task_index=$REPLICA_INDEX --ps_hosts=$PS_NODES --worker_hosts=$WORKER_NODES
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 1
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 4Gi
      port: 2222
      default_volume_mapping: true
    - name: ps
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      is_permanent: true
      images:
        gpu: kuberlab/tensorflow:gpu-27-1.5.0-full
        cpu: kuberlab/tensorflow:cpu-27-1.5.0-full
      command: python styles.py --job_name=ps --task_index=$REPLICA_INDEX --ps_hosts=$PS_NODES --worker_hosts=$WORKER_NODES
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 0
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 4000m
          memory: 4Gi
      port: 2222
      volumes:
      - name: lib
      - name: src
      - name: training
  uix:
  - name: jupyter
    displayName: Jupyter
    images:
      gpu: kuberlab/tensorflow:gpu-27-1.5.0-full
      cpu: kuberlab/tensorflow:cpu-27-1.5.0-full
    resources:
      requests:
        cpu: 100m
        memory: 125Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    default_volume_mapping: true
  - name: tensorboard
    displayName: Tensorboard
    command: "tensorboard"
    args: "--logdir=$TRAINING_DIR"
    images:
      cpu: "kuberlab/tensorflow:cpu-27-1.5.0-base"
    ports:
    - port: 6006
      targetPort: 6006
      protocol: TCP
      name: http
    volumes:
    - name: training
  serving:
  - name: serving
    displayName: TF Serving
    images:
      gpu: "kuberlab/tensorflow-serving:gpu-27-1.5.0"
      cpu: "kuberlab/tensorflow-serving:cpu-27-1.5.0"
    command: tensorflow_model_server
    args: "--port=9000 --model_name=tranform --model_base_path==$checkpoint_path"
    resources:
      accelerators:
        gpu: 1
        dedicated_gpu: true
      requests:
        cpu: 100m
        memory: 125Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    spec:
      params:
      - name: images
        type: bytes
      rawInput: true
      model: tranform
      outMimeType: "image/png"
    ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
    volumes:
    - name: training
  volumes:
  - isLibDir: false
    name: training
    clusterStorage: {{ .storage.value }}
  - gitRepo:
      repository: https://github.com/kuberlab-catalog/styles-transfer-v2
    isLibDir: false
    name: src
    subPath: "styles-transfer-v2/src"
  - isLibDir: true
    name: lib
    clusterStorage: {{ .storage.value }}
  - isLibDir: false
    name: data
    datasetFS:
      workspace: {{ .dataset.workspace }}
      dataset: {{ .dataset.value }}
      version: {{ .dataset.version }}
